# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1718JoBz_rECXbt25y7DoetR2G47JE6ud

AULA 17.08
"""

def media (n1,n2):
  med = (n1+n2) / 2
  print("med final é ",med)

  n1 = float (input("Informe a nota 1: "))
  n2 = float (input("Informe a nota 2: "))

  med(n1,n2)

"""exercicio 2"""

preco = float (input("Digite o preco da mercadoria: "))
desconto = float (input("Digite o percentual de desconto: "))

valor_desconto = preco * desconto / 100
pagamento = preco - valor_desconto

print("O preço é", preco)
print("O desconto é", valor_desconto)
print("Valor a pagar é: ", pagamento)

"""exercicio 3

"""

def percaDias(qtdCigarro, qtdAnos):
    qtdDias = qtdAnos * 365
    minuto = qtdCigarro * 10
    hora = minuto / 60
    dia = hora / 24

    perdaDias = dia * qtdDias
    return perdaDias

    qtdCigarros = 10
    qtdAnos = 2
    resultado = percaDias(qtdCigarros, qtdAnos)
    print(f"A perda estimada de vida em dias é: {resultado} dias")

"""MAQUINA REGISTRADORA


"""

aPagar = 0
while True:
    codigo = int(input("Digite o código do produto: "))
    preco = 0

    if codigo == 0:
        break
    elif codigo == 1:
        preco = 0.50
    elif codigo == 2:
        preco = 1.00
    elif codigo == 3:
        preco = 4.00
    elif codigo == 5:
        preco = 7.00
    elif codigo == 9:
        preco = 8.00
    else:
        print("Código inválido")

    if preco != 0:
        quantidade = int(input("Quantidade: "))
        aPagar = aPagar + (preco * quantidade)
        print(f"Total a pagar é R${aPagar:.2f}")

print("Compra finalizada.")

"""ATV Vetor 14.09"""

vetor = [0] * 4

for i in range (4):
  vetor[i] = int(input("Digite o numero: "))

  x = int(input("Digite uma posição no vetor acima"))
  y = int(input("Digite uma posição no vetor acima"))

  soma = vetor[x] + vetor[y]
  print("A soma de x,y é: ",soma)

"""ATV Vetor 14.09.2"""

vetor = []

for i in range (10):
  vetor.append(int(input("Digite o elemento %d: "%i)))

  maior = vetor [0]
  menor = vetor [0]
  soma = vetor [0]
  media = 0


  for i in range(1, len (vetor)):
    if vetor[i] > maior:
      maior = vetor[i]
    elif vetor[i] < menor:
      menor = vetor[i]

      soma += vetor[i]
      media = soma / len(vetor)

      print("O maior valor é: ",maior)
      print("O menor valor é  ",menor)